quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.show-logs=true


# Connection
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Producer
mp.messaging.outgoing.transactions-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.transactions-out.exchange.name=transactions-exchange
mp.messaging.outgoing.transactions-out.routing-key=transaction.created

# Consumer
mp.messaging.incoming.transactions-in.connector=smallrye-rabbitmq
mp.messaging.incoming.transactions-in.exchange.name=transactions-exchange
mp.messaging.incoming.transactions-in.routing-key=transaction.created
mp.messaging.incoming.transactions-in.queue.name=transactions-queue
mp.messaging.incoming.transactions-in.content-type-override=application/json